// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVYLKQX5TvWwUz4kln7vI43iua2p3ju5A',
    appId: '1:403622029436:web:b52739c5316ed2510c41f9',
    messagingSenderId: '403622029436',
    projectId: 'educational-ab8f0',
    authDomain: 'educational-ab8f0.firebaseapp.com',
    storageBucket: 'educational-ab8f0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOa_Zp4FuLWEDaLf4jfNfX7oOBoIDeJj4',
    appId: '1:403622029436:android:982e44a79e1384da0c41f9',
    messagingSenderId: '403622029436',
    projectId: 'educational-ab8f0',
    storageBucket: 'educational-ab8f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7-sZhJbQG2tpYvLLp1jdTll0ci2Jxk00',
    appId: '1:403622029436:ios:e75c5864e8e1b7e40c41f9',
    messagingSenderId: '403622029436',
    projectId: 'educational-ab8f0',
    storageBucket: 'educational-ab8f0.appspot.com',
    iosBundleId: 'com.example.education',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7-sZhJbQG2tpYvLLp1jdTll0ci2Jxk00',
    appId: '1:403622029436:ios:e75c5864e8e1b7e40c41f9',
    messagingSenderId: '403622029436',
    projectId: 'educational-ab8f0',
    storageBucket: 'educational-ab8f0.appspot.com',
    iosBundleId: 'com.example.education',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVYLKQX5TvWwUz4kln7vI43iua2p3ju5A',
    appId: '1:403622029436:web:48cbfa23ec09659e0c41f9',
    messagingSenderId: '403622029436',
    projectId: 'educational-ab8f0',
    authDomain: 'educational-ab8f0.firebaseapp.com',
    storageBucket: 'educational-ab8f0.appspot.com',
  );
}
